#!/bin/bash
backup(){
cp "$dir/$week.md" "$dir/backup/$week.backup.md"
}
#. "/data/data/com.termux/files/home/caplog.app/orders.ky"
. orders.ky
template="$(cat ~/storage/shared/Ninshu/Templates/CaptainsLogX.md)"
#capdir=$(cat  ~/storage/shared/Ninshu/capdir.md)

week=$(echo "$(date +%Y)-Week $(date +%U)")
### week="2024-Week 52" ###

y=$(echo "$(date +%y)")
### y=24 ###

month=$(echo "$(date +%b)")
### month="Jan" ###

my_date(){
        cero="$(echo "$(date +%d)" | cut -b 1)";
        [ ! "$cero" == '0' ] && dom="$(date +%d)" || dom="$(echo "$(date +%d)" | cut -b 2)"
#       echo "$dom"
#dom=$(my_date)
#wtf=$(my_date)
case "$dom" in
        1 | 21 | 31)
        echo "$dom""st";;
        2 | 22)
        echo "$dom""nd";;
        3 | 23)
        echo "$dom""rd";;
        *)
        echo "$dom""th";;
esac
}
### my_date=26th ###

#dir=$("storage/shared/Ninshu/CaptainsLog/Years/$y/Quarters/Months/Weeks/test>
dir="/data/data/com.termux/files/home/storage/shared/Ninshu/test"

### $dir/$week.md="fulldirectory/2024-Week 52" ###

## tits="get line number from "2024-Week 52" "captains log" then add 2 lines
tits(){ titleraw="$(get_line_number "$dir/$week.md" "Captain's Log")"
title=$((titleraw+2)) &&  echo "$title"
}
#Apr 27th, Sat
#echo "$template" > "$dir/$week.md"
next_day="#### $month ""$(my_date), ""$(date +%a)"
### next_day=Apr 27th, Sat ###

#echo "$next_day" > "$dir/$week.prev"
#[ -f "$dir/$week.md" ] && backup
#[ ! $(date +%a) == "Sun" ] && insert_line_will_ovrwrite_file "$dir/$week.md" "$next_day" "$(tits)"
#[ $(date +%a) == "Sun" ] && echo "$template" > "$dir/$week.md" && insert_line_will_ovrwrite_file "$dir/$week.md" "$next_day" "$(tits)"
